[build]
  functions = "secret-santa/netlify/functions"  # Path to Netlify functions
  publish = "secret-santa/secret-santa/dist"    # Path to the Vite build output


[dev]
  functions = "netlify/functions"
